// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SuperPvp.Core.Transport
{

public enum ObjectType : sbyte
{
 Player = 0,
 Drug = 1,
};


}
