// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SuperPvp.Core.Transport
{

public enum PacketType : sbyte
{
 Undefined = 0,
 Initialize = 1,
 Update = 2,
 Command = 3,
 Finish = 4,
};


}
