// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SuperPvp.Core.Transport
{

using global::System;
using global::FlatBuffers;

public struct Position : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int I { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int J { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<Position> CreatePosition(FlatBufferBuilder builder, int I, int J) {
    builder.Prep(4, 8);
    builder.PutInt(J);
    builder.PutInt(I);
    return new Offset<Position>(builder.Offset);
  }
};


}
